# Generated by Django 4.2.7 on 2024-08-13 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_alter_appuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='draws',
        ),
    ]
