# Generated by Django 4.2.7 on 2024-04-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_appuser_draws_alter_appuser_games_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='oauth_created',
            field=models.BooleanField(default=False),
        ),
    ]
