version: "3"

volumes:
  certs:
    driver: local
  esdata01:
    driver: local
  kibanadata:
    driver: local
  logstashdata01:
    driver: local
  filebeatdata:
    driver: local

services:
  django:
    container_name: django
    depends_on:
      es01:
        condition: service_healthy
      kibana:
        condition: service_healthy
      logstash:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 100
      start_period: 60s

  prometheus:
    image: prom/prometheus:v2.45.6
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      # Data retention and storage strategies
      # https://prometheus.io/docs/prometheus/latest/storage/
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=2d' 
      - '--storage.tsdb.retention.size=80MB'
      # Archiving: https://github.com/prometheus-operator/kube-prometheus/issues/1435#issuecomment-943272922
    ports:
      - "9090:9090"
    networks:
      - t_network

  grafana:
    image: grafana/grafana-oss:11.1.0-ubuntu
    container_name: grafana
    depends_on:
      django:
        condition: service_healthy
    restart: unless-stopped
    environment:
      # increases the log level from info to debug
      - GF_LOG_LEVEL=debug
      - GF_SECURITY_ADMIN_USER=${DB_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${DB_PASSWORD}
    ports:
      - '3000:3000'
    volumes:
      # - ./monitoring/grafana/custom.ini:/etc/grafana/custom.ini
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - ./monitoring/grafana/dashboards/:/var/lib/grafana/dashboards/
      - 'grafana_storage:/var/lib/grafana'
    networks:
      - t_network

  blackbox:
    container_name: blackbox
    image: prom/blackbox-exporter:latest
    # privileged: true
    volumes:
      - ./monitoring/blackbox/config.yml:/etc/blackbox_exporter/config.yml
    ports:
      - '9115:9115'
    networks:
      - t_network

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    # network_mode: host # default port 9100
    ports:
      - '9123:9100'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - t_network

  setup:
    container_name: setup
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - ./monitoring/setup/setup.sh:/root/setup.sh
    user: "0"
    environment:
    - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    - KIBANA_PASSWORD=${KIBANA_PASSWORD}
    command: >
      bash /root/setup.sh
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/es01/es01.crt ]"]
      interval: 1s
      timeout: 5s
      retries: 120
    networks:
      - t_network

  provisioner:
    container_name: provisioner
    depends_on:
      es01:
        condition: service_healthy
    build:
      context: ./monitoring/provisioner
      dockerfile: Dockerfile
    user: "0"
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - ./monitoring/provisioner/provisioner.sh:/tmp/provisioner.sh
    environment:
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
    command:
      - bash 
      - /tmp/provisioner.sh
    networks:
      - t_network

  es01:
    container_name: es01
    depends_on:
      setup:
        condition: service_healthy
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    labels:
      co.elastic.logs/module: elasticsearch
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es01/es01.key
      - xpack.security.http.ssl.certificate=certs/es01/es01.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es01/es01.key
      - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    # mem_limit: ${ES_MEM_LIMIT}
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      - t_network

  kibana:
    container_name: kibana
    depends_on:
      provisioner:
        condition: service_completed_successfully
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    labels:
      co.elastic.logs/module: kibana
    volumes:
      - certs:/usr/share/kibana/config/certs
      - kibanadata:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOST}
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
      - XPACK_SECURITY_ENCRYPTIONKEY=${ENCRYPTION_KEY}
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${ENCRYPTION_KEY}
      - XPACK_REPORTING_ENCRYPTIONKEY=${ENCRYPTION_KEY}
    # mem_limit: ${KB_MEM_LIMIT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      - t_network

  logstash:
    container_name: logstash
    depends_on:
      es01:
        condition: service_healthy
      kibana:
        condition: service_healthy
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    labels:
      co.elastic.logs/module: logstash
    user: root
    volumes:
      - logstashdata01:/usr/share/logstash/data
      - certs:/usr/share/logstash/certs
      - ./monitoring/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - "./log/nginx:/nginx_logs"
      - "./log/django:/django_logs"
    environment:
      - NODE_NAME="logstash"
      - xpack.monitoring.enabled=false
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_HOSTS=https://es01:9200
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044/udp"
    # mem_limit: ${LS_MEM_LIMIT}
    networks:
      - t_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "(curl --silent --fail -s -XGET localhost:9600 | grep -q 'green') || exit 1 ",
        ]
      interval: 10s
      timeout: 10s
      retries: 120