# Generated by Django 4.2.7 on 2024-06-01 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pongGame', '0002_tournaments_remotematch'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
