# Generated by Django 4.2.7 on 2024-08-10 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pongGame', '0005_tournaments_remotematch'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotematch',
            name='match_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
