# Generated by Django 4.2.7 on 2024-08-10 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pongGame', '0005_tournaments_remotematch'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalMatch',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_1', models.CharField(max_length=15)),
                ('player_2', models.CharField(max_length=15)),
                ('rounds_player_1', models.IntegerField(default=0)),
                ('rounds_player_2', models.IntegerField(default=0)),
                ('winner', models.CharField(max_length=15)),
                ('cancelled', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='remotematch',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
