# Generated by Django 4.2.7 on 2024-08-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pongGame', '0006_localmatch_remotematch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='localmatch',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
