# Generated by Django 4.2.7 on 2024-08-11 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pongGame', '0006_remotematch_match_date'),
        ('pongGame', '0007_localmatch_type'),
    ]

    operations = [
    ]
