version: '3.8'

services:
  # django:
  #   depends_on:
  #     - postrgesql
  #   build:
  #     context: .
  #     dockerfile: django/Dockerfile
  #   image: django_server
  #   container_name: django
  #   ports:
  #     - "8000:8000"
  #   # networks:
  #   #   - trancending
  #   volumes:
  #     - ./django/requirements.txt:/var/requirements.txt
  #   env_file:
  #     - .env
  #   restart: always #to be checked

  postrgesql:
    build:
      context: .
      dockerfile: postgresql/Dockerfile
    image: "postgres"
    container_name: "postgres"
    environment:
      POSTGRES_DB : ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    volumes:
      - ./postgresql/config.sql:/docker-entrypoint-initdb.d/config.sql
      - ./postgresql/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports: 
      - "5432:5432"
    restart: unless-stopped
