version: '3.8'

services:
  postgres:
    image: "postgres:16.1"
    container_name: "postgres"
    environment:
      POSTGRES_DB : ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST : ${DB_HOST}
      POSTGRES_PORT : ${DB_PORT}
    volumes:
     - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
     - ./postgresql/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports: 
      - "5432:5432"
    restart: on-failure

  django:
    container_name: django_web
    build:
      context: ./django
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./django/backend:/code
      - ./django/start.sh:/code/start.sh
    depends_on:
      - postgres
    env_file:
      - .env
    restart: on-failure


