version: '3.8'

services:
  django:
    container_name: django_web
    build:
      context: ./django
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./django/backend:/code
    depends_on:
    - postgresql
    # env_file:
    #   - .env
    networks:
      - yourmom

  postgresql:
    build:
      context: .
      dockerfile: postgresql/Dockerfile
    image: "postgres"
    container_name: "postgres"
    environment:
      POSTGRES_DB : ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    volumes:
     - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
     - ./postgresql/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports: 
      - "5432:5432"
    networks:
      - yourmom
    restart: unless-stopped


networks:
  yourmom:
    driver: bridge
    name: yourmom


# services:
#   django:
#     depends_on:
#       - postrgesql
#     build:
#       context: .
#       dockerfile: django/Dockerfile
#     image: backend
#     container_name: django
#     ports:
#       - "8000:8000"
#     # networks:
#     #   - trancending
#     volumes:
#       - ./django/requirements.txt:/var/requirements.txt
#     env_file:
#       - .env
#     restart: always #to be checked

